### ISSUE TITLE
Bug:  GeoIP crashes when encountering a 100.64.0.0/10 address.

### ISSUE THREAD

**Issue by quadrantsec** [quadrantsec/sagan#79]
100.64.0.0/10 is a private network block that is being labeled as CN. 

Debug output:

``
[D] ----------------------------------------------------------------
[D] GeoIP Lookup IP               : 100.66.86.3
[D] ----------------------------------------------------------------
[D] Country                       : CN
[D] GeoIP Lookup IP               : 100.66.190.21
[D] City                          : �0�
[D] Country                       : CN
[D] Subdivision                   :
[D] User Defined Country Codes    : US
[D] ----------------------------------------------------------------
[D] City                          : 1���
[D] GeoIP rule string parsing     : US|CN
[D] GeoIP Lookup IP               : 100.66.175.95
[D] Subdivision                   :
[D] Country                       : CN
[D] GeoIP Lookup IP               : 100.66.144.11
[D] GeoIP Status: Not found in user defined values.
[D] City                          : ��x�
[D] User Defined Country Codes    : US
[D] Country                       : CN
[D] GeoIP rule string parsing     : US|CN
[D] City                          : ჴ�
[D] GeoIP Status: Not found in user defined values.
``

Below is gdb backtrace:

``
[D] GeoIP Status: Not found in user defined values.

Thread 31 "SaganProcessor" received signal SIGBUS, Bus error.
[Switching to Thread 0x7ffe26ffd700 (LWP 803938)]
__vsnprintf_internal (string=0x6c6169746e656465 <error: Cannot access memory at address 0x6c6169746e656465>, maxlen=<optimized out>, format=0x55555559d8f5 "%s:%s:%s:%s", args=args@entry=0x7ffe26ffbac0, mode_flags=mode_flags@entry=0) at vsnprintf.c:112
112     vsnprintf.c: No such file or directory.
(gdb) bt
#0  __vsnprintf_internal (string=0x6c6169746e656465 <error: Cannot access memory at address 0x6c6169746e656465>, maxlen=<optimized out>, format=0x55555559d8f5 "%s:%s:%s:%s", args=args@entry=0x7ffe26ffbac0, mode_flags=mode_flags@entry=0) at vsnprintf.c:112
#1  0x00007ffff79c1e52 in __GI___snprintf (s=<optimized out>, maxlen=maxlen@entry=8, format=format@entry=0x55555559d8f5 "%s:%s:%s:%s") at snprintf.c:31
#2  0x00005555555764dd in Xbit_Set_Redis (rule_position=132, SaganProcSyslog_LOCAL=0x7ffe08000c90) at xbit-redis.c:209
#3  0x0000555555575175 in Xbit_Set (rule_position=rule_position@entry=132, SaganProcSyslog_LOCAL=SaganProcSyslog_LOCAL@entry=0x7ffe08000c90) at xbit.c:61
#4  0x00005555555870a1 in Sagan_Engine (SaganProcSyslog_LOCAL=SaganProcSyslog_LOCAL@entry=0x7ffe08000c90, JSON_LOCAL=JSON_LOCAL@entry=0x7ffe0802b930, dynamic_rule_flag=false) at processors/engine.c:1390
#5  0x000055555556d95c in Processor () at processor.c:274
#6  0x00007ffff7c8eea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff7a6aa2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
``

**Comment by quadrantsec** [comment]
Fixed.  Pushed for testing.
